import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useUpdateCustomer, Customer } from "@/hooks/useCustomers";
import { useReps } from "@/hooks/useReps";
import { toast } from "sonner";
import { X, Save, UserCheck } from "lucide-react";

interface EditCustomerModalProps {
    customer: Customer | null;
    isOpen: boolean;
    onClose: () => void;
    onDismiss?: (kundenNummer: number) => void;
}

export function EditCustomerModal({ customer, isOpen, onClose, onDismiss }: EditCustomerModalProps) {
    const { data: reps } = useReps();
    const updateCustomer = useUpdateCustomer();

    const [formData, setFormData] = useState({
        email: "",
        ort: "",
        plz: "",
        strasse: "",
        telefon: "",
        mobil: "",
        rep_id: "",
    });

    // Sync form data when customer changes
    useEffect(() => {
        if (customer) {
            setFormData({
                email: customer.email || "",
                ort: customer.ort || "",
                plz: customer.plz || "",
                strasse: customer.strasse || "",
                telefon: customer.telefon || "",
                mobil: customer.mobil || "",
                rep_id: customer.rep_id?.toString() || "",
            });
        }
    }, [customer]);

    const handleSave = async () => {
        if (!customer) return;

        // Calculate new u_key - handle both formats: 'auto_' and 'AUTOGENERATED|'
        const isAutoGenerated = customer.u_key?.startsWith("auto_") || customer.u_key?.startsWith("AUTOGENERATED|");
        let newUKey = customer.u_key;
        if (isAutoGenerated) {
            if (customer.u_key?.startsWith("auto_")) {
                newUKey = customer.u_key.replace("auto_", "reviewed_");
            } else if (customer.u_key?.startsWith("AUTOGENERATED|")) {
                newUKey = customer.u_key.replace("AUTOGENERATED|", "REVIEWED|");
            }
        }

        console.log("Saving customer:", {
            kunden_nummer: customer.kunden_nummer,
            originalUKey: customer.u_key,
            newUKey: newUKey,
            isAutoGenerated: isAutoGenerated
        });

        try {
            const result = await updateCustomer.mutateAsync({
                kunden_nummer: customer.kunden_nummer,
                updates: {
                    email: formData.email || null,
                    ort: formData.ort || null,
                    plz: formData.plz || null,
                    strasse: formData.strasse || null,
                    telefon: formData.telefon || null,
                    mobil: formData.mobil || null,
                    rep_id: formData.rep_id ? parseInt(formData.rep_id) : null,
                    // Remove auto_ prefix to mark as reviewed
                    u_key: newUKey,
                },
            });

            console.log("Update result:", result);
            toast.success("Kundendaten erfolgreich gespeichert");
            onClose();
        } catch (error) {
            toast.error("Fehler beim Speichern");
            console.error("Update error:", error);
        }
    };

    const handleDismiss = async () => {
        if (!customer) return;

        try {
            // Mark as reviewed by changing prefix - handle both formats
            const isAutoGenerated = customer.u_key?.startsWith("auto_") || customer.u_key?.startsWith("AUTOGENERATED|");
            let newUKey = customer.u_key;
            if (isAutoGenerated) {
                if (customer.u_key?.startsWith("auto_")) {
                    newUKey = customer.u_key.replace("auto_", "reviewed_");
                } else if (customer.u_key?.startsWith("AUTOGENERATED|")) {
                    newUKey = customer.u_key.replace("AUTOGENERATED|", "REVIEWED|");
                }
            }

            await updateCustomer.mutateAsync({
                kunden_nummer: customer.kunden_nummer,
                updates: {
                    u_key: newUKey,
                },
            });

            toast.success("Kunde als überprüft markiert");
            if (onDismiss) {
                onDismiss(customer.kunden_nummer);
            }
            onClose();
        } catch (error) {
            toast.error("Fehler beim Markieren");
            console.error(error);
        }
    };

    if (!customer) return null;

    const isAutoGenerated = (customer.u_key?.startsWith("auto_") || customer.u_key?.startsWith("AUTOGENERATED|")) ?? false;

    return (
        <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
            <DialogContent className="max-w-lg">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2">
                        <UserCheck className="h-5 w-5" />
                        Kunde bearbeiten
                    </DialogTitle>
                    <DialogDescription>
                        <span className="font-semibold">{customer.firma}</span>
                        <span className="text-muted-foreground ml-2">(Kd.-Nr: {customer.kunden_nummer})</span>
                    </DialogDescription>
                </DialogHeader>

                <div className="grid gap-4 py-4">
                    {/* Email */}
                    <div className="grid gap-2">
                        <Label htmlFor="email">E-Mail</Label>
                        <Input
                            id="email"
                            type="email"
                            placeholder="email@beispiel.de"
                            value={formData.email}
                            onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                        />
                    </div>

                    {/* Address Row */}
                    <div className="grid grid-cols-3 gap-3">
                        <div className="col-span-2 grid gap-2">
                            <Label htmlFor="strasse">Straße</Label>
                            <Input
                                id="strasse"
                                placeholder="Musterstraße 1"
                                value={formData.strasse}
                                onChange={(e) => setFormData({ ...formData, strasse: e.target.value })}
                            />
                        </div>
                        <div className="grid gap-2">
                            <Label htmlFor="plz">PLZ</Label>
                            <Input
                                id="plz"
                                placeholder="12345"
                                value={formData.plz}
                                onChange={(e) => setFormData({ ...formData, plz: e.target.value })}
                            />
                        </div>
                    </div>

                    {/* Ort */}
                    <div className="grid gap-2">
                        <Label htmlFor="ort">Ort</Label>
                        <Input
                            id="ort"
                            placeholder="Berlin"
                            value={formData.ort}
                            onChange={(e) => setFormData({ ...formData, ort: e.target.value })}
                        />
                    </div>

                    {/* Phone Row */}
                    <div className="grid grid-cols-2 gap-3">
                        <div className="grid gap-2">
                            <Label htmlFor="telefon">Telefon</Label>
                            <Input
                                id="telefon"
                                placeholder="030 12345678"
                                value={formData.telefon}
                                onChange={(e) => setFormData({ ...formData, telefon: e.target.value })}
                            />
                        </div>
                        <div className="grid gap-2">
                            <Label htmlFor="mobil">Mobil</Label>
                            <Input
                                id="mobil"
                                placeholder="0170 1234567"
                                value={formData.mobil}
                                onChange={(e) => setFormData({ ...formData, mobil: e.target.value })}
                            />
                        </div>
                    </div>

                    {/* Rep Selection */}
                    <div className="grid gap-2">
                        <Label htmlFor="rep">Außendienstler</Label>
                        <Select
                            value={formData.rep_id}
                            onValueChange={(value) => setFormData({ ...formData, rep_id: value })}
                        >
                            <SelectTrigger>
                                <SelectValue placeholder="Außendienstler auswählen..." />
                            </SelectTrigger>
                            <SelectContent>
                                {reps?.map((rep) => (
                                    <SelectItem key={rep.rep_id} value={rep.rep_id.toString()}>
                                        {rep.name}
                                    </SelectItem>
                                ))}
                            </SelectContent>
                        </Select>
                    </div>
                </div>

                <DialogFooter className="flex gap-2 sm:gap-0">
                    {isAutoGenerated && (
                        <Button variant="outline" onClick={handleDismiss} className="gap-2">
                            <X className="h-4 w-4" />
                            Überspringen
                        </Button>
                    )}
                    <Button onClick={handleSave} disabled={updateCustomer.isPending} className="gap-2">
                        <Save className="h-4 w-4" />
                        Speichern
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
