import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from "@/shared/components/ui/dialog";
import { Button } from "@/shared/components/ui/button";
import { Input } from "@/shared/components/ui/input";
import { Label } from "@/shared/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/components/ui/select";
import { useUpdateCustomer, Customer } from "@/features/customers/hooks/useCustomers";
import { useReps } from "@/features/reps/hooks/useReps";
import { toast } from "sonner";
import { X, Save, UserCheck, Clock } from "lucide-react";
import { OpeningHoursPicker } from "@/features/customers/components/OpeningHoursPicker";
import { useQueryClient } from "@tanstack/react-query";

interface EditCustomerModalProps {
    customer: Customer | null;
    isOpen: boolean;
    onClose: () => void;
    onDismiss?: (kundenNummer: number) => void;
    isRepView?: boolean;
}

const DAYS = [
    { key: 'mon', label: 'Mo' },
    { key: 'tue', label: 'Di' },
    { key: 'wed', label: 'Mi' },
    { key: 'thu', label: 'Do' },
    { key: 'fri', label: 'Fr' },
    { key: 'sat', label: 'Sa' },
    { key: 'sun', label: 'So' },
] as const;

export function EditCustomerModal({ customer, isOpen, onClose, onDismiss, isRepView = false }: EditCustomerModalProps) {
    const { data: reps } = useReps();
    const updateCustomer = useUpdateCustomer();
    const queryClient = useQueryClient();

    const [formData, setFormData] = useState({
        email: "",
        ort: "",
        plz: "",
        strasse: "",
        telefon: "",
        mobil: "",
        rep_id: "",
        opening_hours_mon: "",
        opening_hours_tue: "",
        opening_hours_wed: "",
        opening_hours_thu: "",
        opening_hours_fri: "",
        opening_hours_sat: "",
        opening_hours_sun: "",
        opening_hours_notes: "",
    });

    useEffect(() => {
        if (customer) {
            setFormData({
                email: customer.email || "",
                ort: customer.ort || "",
                plz: customer.plz || "",
                strasse: customer.strasse || "",
                telefon: customer.telefon || "",
                mobil: customer.mobil || "",
                rep_id: customer.rep_id?.toString() || "",
                opening_hours_mon: customer.opening_hours_mon || "",
                opening_hours_tue: customer.opening_hours_tue || "",
                opening_hours_wed: customer.opening_hours_wed || "",
                opening_hours_thu: customer.opening_hours_thu || "",
                opening_hours_fri: customer.opening_hours_fri || "",
                opening_hours_sat: customer.opening_hours_sat || "",
                opening_hours_sun: customer.opening_hours_sun || "",
                opening_hours_notes: customer.opening_hours_notes || "",
            });
        }
    }, [customer]);

    const handleOpeningHoursChange = (day: string, value: string) => {
        const fieldKey = `opening_hours_${day}` as keyof typeof formData;
        setFormData(prev => ({ ...prev, [fieldKey]: value }));
    };

    const copyToAllDays = () => {
        const monValue = formData.opening_hours_mon;
        if (!monValue) {
            toast.error("Bitte zuerst Montag einstellen");
            return;
        }

        setFormData(prev => ({
            ...prev,
            opening_hours_tue: monValue,
            opening_hours_wed: monValue,
            opening_hours_thu: monValue,
            opening_hours_fri: monValue,
            opening_hours_sat: monValue,
            opening_hours_sun: monValue,
        }));
        toast.success("Öffnungszeiten auf alle Tage kopiert");
    };

    const handleSave = async () => {
        if (!customer) return;

        const isAutoGenerated = customer.u_key?.startsWith("auto_") || customer.u_key?.startsWith("AUTOGENERATED|");
        let newUKey = customer.u_key;
        if (isAutoGenerated) {
            if (customer.u_key?.startsWith("auto_")) {
                newUKey = customer.u_key.replace("auto_", "reviewed_");
            } else if (customer.u_key?.startsWith("AUTOGENERATED|")) {
                newUKey = customer.u_key.replace("AUTOGENERATED|", "REVIEWED|");
            }
        }

        try {
            await updateCustomer.mutateAsync({
                kunden_nummer: customer.kunden_nummer,
                updates: {
                    email: formData.email || null,
                    ort: formData.ort || null,
                    plz: formData.plz || null,
                    strasse: formData.strasse || null,
                    telefon: formData.telefon || null,
                    mobil: formData.mobil || null,
                    ...(isRepView ? {} : { rep_id: formData.rep_id ? parseInt(formData.rep_id) : null }),
                    opening_hours_mon: formData.opening_hours_mon || null,
                    opening_hours_tue: formData.opening_hours_tue || null,
                    opening_hours_wed: formData.opening_hours_wed || null,
                    opening_hours_thu: formData.opening_hours_thu || null,
                    opening_hours_fri: formData.opening_hours_fri || null,
                    opening_hours_sat: formData.opening_hours_sat || null,
                    opening_hours_sun: formData.opening_hours_sun || null,
                    opening_hours_notes: formData.opening_hours_notes || null,
                    u_key: newUKey,
                },
            });

            // Invalidate queries to refresh data
            queryClient.invalidateQueries({ queryKey: ["customers"] });

            toast.success("Kundendaten erfolgreich gespeichert");
            onClose();
        } catch (error) {
            toast.error("Fehler beim Speichern");
            console.error("Update error:", error);
        }
    };

    const handleDismiss = async () => {
        if (!customer) return;

        try {
            const isAutoGenerated = customer.u_key?.startsWith("auto_") || customer.u_key?.startsWith("AUTOGENERATED|");
            let newUKey = customer.u_key;
            if (isAutoGenerated) {
                if (customer.u_key?.startsWith("auto_")) {
                    newUKey = customer.u_key.replace("auto_", "reviewed_");
                } else if (customer.u_key?.startsWith("AUTOGENERATED|")) {
                    newUKey = customer.u_key.replace("AUTOGENERATED|", "REVIEWED|");
                }
            }

            await updateCustomer.mutateAsync({
                kunden_nummer: customer.kunden_nummer,
                updates: {
                    u_key: newUKey,
                },
            });

            toast.success("Kunde als überprüft markiert");
            if (onDismiss) {
                onDismiss(customer.kunden_nummer);
            }
            onClose();
        } catch (error) {
            toast.error("Fehler beim Markieren");
            console.error(error);
        }
    };

    if (!customer) return null;

    const isAutoGenerated = (customer.u_key?.startsWith("auto_") || customer.u_key?.startsWith("AUTOGENERATED|")) ?? false;

    return (
        <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
            <DialogContent className="max-w-md max-h-[90vh] overflow-y-auto">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2">
                        <UserCheck className="h-5 w-5" />
                        Kunde bearbeiten
                    </DialogTitle>
                    <DialogDescription>
                        <span className="font-semibold">{customer.firma}</span>
                        <span className="text-muted-foreground ml-2">(#{customer.kunden_nummer})</span>
                    </DialogDescription>
                </DialogHeader>

                <div className="grid gap-4 py-4">
                    {/* Contact Info */}
                    <div className="grid gap-2">
                        <Label htmlFor="email">E-Mail</Label>
                        <Input
                            id="email"
                            type="email"
                            placeholder="email@beispiel.de"
                            value={formData.email}
                            onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                        />
                    </div>

                    <div className="grid grid-cols-3 gap-2">
                        <div className="col-span-2">
                            <Label htmlFor="strasse">Straße</Label>
                            <Input
                                id="strasse"
                                placeholder="Musterstraße 1"
                                value={formData.strasse}
                                onChange={(e) => setFormData({ ...formData, strasse: e.target.value })}
                            />
                        </div>
                        <div>
                            <Label htmlFor="plz">PLZ</Label>
                            <Input
                                id="plz"
                                placeholder="12345"
                                value={formData.plz}
                                onChange={(e) => setFormData({ ...formData, plz: e.target.value })}
                            />
                        </div>
                    </div>

                    <div className="grid gap-2">
                        <Label htmlFor="ort">Ort</Label>
                        <Input
                            id="ort"
                            placeholder="Berlin"
                            value={formData.ort}
                            onChange={(e) => setFormData({ ...formData, ort: e.target.value })}
                        />
                    </div>

                    <div className="grid grid-cols-2 gap-2">
                        <div>
                            <Label htmlFor="telefon">Telefon</Label>
                            <Input
                                id="telefon"
                                placeholder="030 12345678"
                                value={formData.telefon}
                                onChange={(e) => setFormData({ ...formData, telefon: e.target.value })}
                            />
                        </div>
                        <div>
                            <Label htmlFor="mobil">Mobil</Label>
                            <Input
                                id="mobil"
                                placeholder="0170 1234567"
                                value={formData.mobil}
                                onChange={(e) => setFormData({ ...formData, mobil: e.target.value })}
                            />
                        </div>
                    </div>

                    {!isRepView && (
                        <div className="grid gap-2">
                            <Label htmlFor="rep">Außendienstler</Label>
                            <Select
                                value={formData.rep_id}
                                onValueChange={(value) => setFormData({ ...formData, rep_id: value })}
                            >
                                <SelectTrigger>
                                    <SelectValue placeholder="Auswählen..." />
                                </SelectTrigger>
                                <SelectContent>
                                    {reps?.map((rep) => (
                                        <SelectItem key={rep.rep_id} value={rep.rep_id.toString()}>
                                            {rep.name}
                                        </SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>
                    )}

                    {/* Opening Hours Section */}
                    <div className="border-t pt-4 mt-2">
                        <div className="flex items-center gap-2 mb-3">
                            <Clock className="h-4 w-4" />
                            <Label className="text-base font-semibold">Öffnungszeiten</Label>
                        </div>

                        <div className="space-y-1">
                            {DAYS.map((day, index) => (
                                <OpeningHoursPicker
                                    key={day.key}
                                    label={day.label}
                                    value={formData[`opening_hours_${day.key}` as keyof typeof formData]}
                                    onChange={(value) => handleOpeningHoursChange(day.key, value)}
                                    showCopyButton={index === 0}
                                    onCopyToAll={copyToAllDays}
                                />
                            ))}
                        </div>

                        <div className="mt-3">
                            <Label htmlFor="opening_notes" className="text-sm">Zusätzliche Hinweise</Label>
                            <Input
                                id="opening_notes"
                                placeholder="z.B. Küche bis 21:00"
                                value={formData.opening_hours_notes}
                                onChange={(e) => setFormData({ ...formData, opening_hours_notes: e.target.value })}
                                className="mt-1"
                            />
                        </div>
                    </div>
                </div>

                <DialogFooter className="flex gap-2 sm:gap-0">
                    {isAutoGenerated && !isRepView && (
                        <Button variant="outline" onClick={handleDismiss} className="gap-2">
                            <X className="h-4 w-4" />
                            Überspringen
                        </Button>
                    )}
                    <Button onClick={handleSave} disabled={updateCustomer.isPending} className="gap-2">
                        <Save className="h-4 w-4" />
                        Speichern
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
