// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfxhqpjnlhxzmsxeszdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmeGhxcGpubGh4em1zeGVzemRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4NjgxNzgsImV4cCI6MjA3NjQ0NDE3OH0.DKQ0BogDdPPElcUW5M_97kTcx8spoqzfyar9mjHRcyQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});